### ISSUE TITLE
settings for folders read only by default

### ISSUE THREAD

**Issue by tynsh** [FachschaftMathPhys/moozean#43]
I think an additional button to switch to editing should be created. By default these settings should be displayed but not editable.

**Comment by Sedrunum** [comment]
An additional button would prolong the deletion process as it became necessary to hit two buttons instead of a single click but I understand your concern of accidentially deleting a folder. An alternative proposal: The editing dialogue stays the same as there is no danger of unintentionally deleting the folder. A second deletion dialogue is added to prevent removal by mistake.

**Comment by tynsh** [comment]
I think it does not matter how long the deletion process takes. This is
something that is almost never done. In the old system we used the user had
to edit the database directly and as far as I know no folder was deleted in
the last 7 years.

The same applies to nearly all other settings. To make things easier you
could strip the settings from the folder section and make them
accessible via a button. So all in all the folder page would just contain the
subfolders and the settings button. If that is hard to implement your
proposal is also okay but honestly I think it is still confusing for the
user.
